# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-09 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=38)),
                ('team_name', models.CharField(max_length=38)),
                ('primary_color', models.CharField(max_length=38)),
                ('secondary_color', models.CharField(max_length=38)),
                ('third_color', models.CharField(max_length=38)),
                ('primary_hex', models.CharField(max_length=38)),
                ('secondary_hex', models.CharField(max_length=38)),
                ('third_hex', models.CharField(max_length=38)),
                ('website', models.URLField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
